// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carbon: logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'Carbon:arrowRight': typeof import('~icons/carbon/arrow-right')['default']
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    Home: typeof import('./theme/view/Home.vue')['default']
    HomeFeatures: typeof import('./theme/view/HomeFeatures.vue')['default']
    HomeHero: typeof import('./theme/view/HomeHero.vue')['default']
  }

}
